{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ingress-hub.fullname" . }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName := include "ingress-hub.fullname" $ }}
                name: {{ $fullName }}
                port:
                  number: 8080
        {{- end }}
  {{- end }}
{{- end }}
