apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ingress-hub.name" . }}
  annotations:
{{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  labels:
{{- toYaml .Values.serviceAccount.extraLabels | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ingress-hub.name" . }}
  annotations:
{{- toYaml .Values.clusterRole.annotations | nindent 4 }}
  labels:
{{- toYaml .Values.clusterRole.extraLabels | nindent 4 }}
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingressclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ingress-hub.name" . }}
  annotations:
{{- toYaml .Values.clusterRoleBinding.annotations | nindent 4 }}
  labels:
{{- toYaml .Values.clusterRoleBinding.extraLabels | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "ingress-hub.name" . }}
  namespace: {{ include "ingress-hub.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "ingress-hub.name" . }}
  apiGroup: rbac.authorization.k8s.io
