apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingress-hub.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: {{ .Values.app.port }}
  selector:
    app: {{ include "ingress-hub.name" . }}
