deployment:
  annotations: {}
  extraLabels: {}
  replicaCount: 1
  image:
    repository: guillh/k8-ingress-hub
    tag: 0.0.1


app:
  port: 8080
  htmlDir: /www/html

service:
  annotations: {}
  extraLabels: {}
  type: ClusterIP

ingress:
  enabled: false
  hostname: ingress-hub.example.io
  tls: 
    enabled: false
    secretName: null
  ingressClassName: ""
  annotations: {}
  extraLabels: {}

serviceAccount:
  annotations: {}
  extraLabels: {}

clusterRole:
  annotations: {}
  extraLabels: {}

clusterRoleBinding:
  annotations: {}
  extraLabels: {}